# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
   pull_request:
    branches: [master]
    types: [closed]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    name: Release notes generator
    steps:
    - uses: actions/checkout@master
    - name: Create Release Notes
      uses: docker://decathlon/release-notes-generator-action:2.0.1
      env:
        OUTPUT_FOLDER: temp_release_notes
        USE_MILESTONE_TITLE: "true"
